version: '3'
services:
  php:
    build: .
    volumes:
       - ./htdocs:/htdocs
       - ./php.ini:/usr/local/etc/php/php.ini
  nginx:
    image: "nginx:alpine"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./vhosts:/etc/nginx/vhosts
      - ./htdocs:/htdocs
    depends_on:
      - php
    ports:
      - "80:80"
    links:
      - "php:php"